FROM golang:1.14-alpine

RUN apk add --update make gcc linux-headers build-base

WORKDIR /usr/src/app
COPY . .
RUN go get github.com/cespare/reflex
RUN go get ./...

ENV "ENV" "development"
CMD [ "make", "endpoint-test"]
